from .register_form_graduated import RegisterFormGraduated
from .register_form_admin import RegisterFormAdmin
from .create_form_category import CreateFormCategory
from .create_form_activity import CreateFormActivity