# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('colombia', 'Colombia')], max_length=30)),
                ('birthday', models.DateField()),
                ('genre', models.CharField(choices=[('male', 'Hombre'), ('female', 'Mujer')], max_length=10)),
                ('graduation_year', models.DateField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Career')),
                ('categories', models.ManyToManyField(to='domain.Category')),
            ],
            options={
                'verbose_name_plural': 'PreRegisters',
                'verbose_name': 'PreRegister',
            },
        ),
    ]
