# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_preregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
