# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20171003_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregister',
            name='categories',
        ),
    ]
