# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_remove_preregister_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregister',
            name='genre',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10),
        ),
    ]
