# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20171010_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisterAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('colombia', 'Colombia')], max_length=30)),
                ('genre', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10)),
                ('cellphone', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'PreRegistersAdmins',
                'verbose_name': 'PreRegisterAdmin',
            },
        ),
        migrations.RenameModel(
            old_name='PreRegister',
            new_name='PreRegisterGraduated',
        ),
        migrations.AlterModelOptions(
            name='preregistergraduated',
            options={'verbose_name': 'PreRegisterGraduated', 'verbose_name_plural': 'PreRegistersGraduatedes'},
        ),
    ]
