# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregisteradmin',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Country'),
        ),
        migrations.AlterField(
            model_name='preregistergraduated',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Country'),
        ),
    ]
