# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_auto_20171111_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduated',
            name='fisrt_login',
            field=models.BooleanField(default=True),
        ),
    ]
