# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_graduated_fisrt_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduated',
            old_name='fisrt_login',
            new_name='first_login',
        ),
    ]
