# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_admin_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(default=True, upload_to='web/profile_pictures'),
        ),
    ]
