# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_auto_20171110_1858'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='admin',
            name='cellphone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(default=True, null=True, upload_to='profile_pictures'),
        ),
    ]
