# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0017_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Category'),
        ),
    ]
