# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_auto_20171111_1531'),
        ('domain', '0018_activity_category'),
    ]

    operations = [
    ]
