# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0020_auto_20171111_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduated',
            name='categories',
        ),
        migrations.AddField(
            model_name='graduated',
            name='preferences',
            field=models.ManyToManyField(to='domain.Category'),
        ),
    ]
