# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0022_graduated_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
