# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0023_auto_20171118_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduated',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
