# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0025_auto_20171121_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 18, 46, 33, 86410, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='last_modification',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 21, 18, 46, 46, 130953, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
