# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0026_auto_20171121_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_activity',
            field=models.DateField(default=datetime.datetime(2017, 11, 21, 19, 46, 54, 688514, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time_activity',
            field=models.TimeField(default=datetime.datetime(2017, 11, 21, 19, 47, 34, 818677, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
