# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0027_auto_20171121_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 19, 39, 45, 164079, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
