# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0029_auto_20171123_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduated',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='graduated',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
