# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0030_auto_20171123_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=1000)),
                ('to_email', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('date_email', models.DateField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.AddField(
            model_name='graduated',
            name='historial',
            field=models.ManyToManyField(to='domain.Historial'),
        ),
    ]
