# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0033_remove_graduated_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='from_user',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='to_user',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
