# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0034_auto_20171204_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='from_user',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historial',
            name='to_user',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
