# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0035_auto_20171204_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='to_user',
        ),
    ]
